### DISCUSSION TITLE
How to change weight / stroke width

### DISCUSSION THREAD

**Discussion by zjael** [antfu/unplugin-icons#345] [Q&A]
Hi, I can't seem to get "Material Symbols" in this case to react to any stroke width or font weight/variation settings, is there something I overlooked?

Is it possible to override the font variation settings like? 
```css
.material-symbols-outlined { 
  font-variation-settings: 
    'FILL' 0, 
    'wght' 400, 
    'GRAD' 0, 
    'opsz' 24 
}
```
